// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/genres/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/genres/[id].delete').default>>>>
    }
    '/api/genres': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/genres/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/genres/index.post').default>>>>
    }
    '/api/languages/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/languages/[id].delete').default>>>>
    }
    '/api/languages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/languages/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/languages/index.post').default>>>>
    }
    '/api/problems/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/problems/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/problems/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/problems/[id].put').default>>>>
    }
    '/api/problems/count': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/problems/count.get').default>>>>
    }
    '/api/problems/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/problems/import.post').default>>>>
    }
    '/api/problems': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/problems/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/problems/index.post').default>>>>
    }
    '/api/problems/random': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/problems/random.get').default>>>>
    }
    '/api/problems/review': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/problems/review.get').default>>>>
    }
    '/api/sessions/:id/end': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sessions/[id]/end.post').default>>>>
    }
    '/api/sessions/:id/records': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sessions/[id]/records.post').default>>>>
    }
    '/api/sessions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sessions/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sessions/index.post').default>>>>
    }
    '/api/stats/calendar': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats/calendar.get').default>>>>
    }
    '/api/stats/daily': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats/daily.get').default>>>>
    }
    '/api/stats/export': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats/export.get').default>>>>
    }
    '/api/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats/index.get').default>>>>
    }
    '/api/stats/monthly': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats/monthly.get').default>>>>
    }
    '/api/stats/problems': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats/problems.get').default>>>>
    }
    '/api/stats/recent-sessions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats/recent-sessions.get').default>>>>
    }
    '/api/stats/weak-problems': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats/weak-problems.get').default>>>>
    }
    '/api/stats/weekly': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats/weekly.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}