// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/18/2025, 9:33:53 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/uchoso/quiz/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/uchoso/quiz/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/uchoso/quiz/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/uchoso/quiz/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/uchoso/quiz/plugins/**/*.{js,ts,mjs}","/home/uchoso/quiz/composables/**/*.{js,ts,mjs}","/home/uchoso/quiz/utils/**/*.{js,ts,mjs}","/home/uchoso/quiz/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/uchoso/quiz/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/uchoso/quiz/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/uchoso/quiz/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;